# THIS FILE IS AUTOGENERATED

from mudata_explorer import app
from muon import MuData


def markdown(
    mdata: MuData,
    text=''
):
    """
    Write any text using markdown syntax.
    """

    app.add_view(
        'markdown',
        mdata,
        params={
            'text': text
        }
    )
