# THIS FILE IS AUTOGENERATED

from mudata_explorer import app
from mudata_explorer.sdk.helpers import collapse_params
from muon import MuData


def markdown(
    mdata: MuData,
    text='',
    **extra_params
):
    """
    Write any text using markdown syntax.
    """

    assert isinstance(mdata, MuData), "mdata must be a MuData object"
    extra_params = collapse_params(extra_params)

    app.add_view(
        'markdown',
        mdata,
        params={
            'text': extra_params.get('text', text)
        }
    )
