# THIS FILE IS AUTOGENERATED

from mudata_explorer.sdk.helpers import collapse_params
from mudata_explorer.helpers.add_view import add_view
from muon import MuData


def plotly_box_multiple(
    mdata: MuData,
    table_data_axis=0,
    table_data_tables=[],
    table_data_rows_query_query_type='',
    table_data_rows_query_query_table='',
    table_data_rows_query_query_cname='',
    table_data_rows_query_query_expr='',
    table_data_rows_query_query_value='',
    table_data_cols_query_query_type='',
    table_data_cols_query_query_table='',
    table_data_cols_query_query_cname='',
    table_data_cols_query_query_expr='',
    table_data_cols_query_query_value='',
    table_data_transforms=[],
    table_category_enabled=True,
    table_category_axis=0,
    table_category_category_table=None,
    table_category_category_cname=None,
    table_category_category_label='Category',
    table_category_rows_query_query_type='',
    table_category_rows_query_query_table='',
    table_category_rows_query_query_cname='',
    table_category_rows_query_query_expr='',
    table_category_rows_query_query_value='',
    table_category_cols_query_query_type='',
    table_category_cols_query_query_table='',
    table_category_cols_query_query_cname='',
    table_category_cols_query_query_expr='',
    table_category_cols_query_query_value='',
    table_category_transforms=[],
    variable_options_axis='Y-Axis',
    variable_options_log_values=None,
    variable_options_sort_by='Mean',
    category_options_axis='Axis',
    category_options_sort_by='Mean',
    display_options_ncols=1,
    display_options_outliers_enabled=True,
    display_options_title='',
    display_options_var_label='Variable',
    display_options_val_label='Value',
    display_options_height=500,
    **extra_params
):
    """
    
    Display multiple columns of data as a box graph using Plotly, summarizing
    the data in terms of the median, quartiles, and outliers.

    A collection of columns are used to define the values on the y-axis, and a
    second column is used for the categorical groups which are
    displayed on the x-axis.
    
    """

    assert isinstance(mdata, MuData), "mdata must be a MuData object"
    extra_params = collapse_params(extra_params)

    add_view(
        'plotly-box-multiple',
        mdata,
        params={
            'table.data.axis': extra_params.get('table_data_axis', table_data_axis),
            'table.data.tables': extra_params.get('table_data_tables', table_data_tables),
            'table.data.rows_query.query.type': extra_params.get('table_data_rows_query_query_type', table_data_rows_query_query_type),
            'table.data.rows_query.query.table': extra_params.get('table_data_rows_query_query_table', table_data_rows_query_query_table),
            'table.data.rows_query.query.cname': extra_params.get('table_data_rows_query_query_cname', table_data_rows_query_query_cname),
            'table.data.rows_query.query.expr': extra_params.get('table_data_rows_query_query_expr', table_data_rows_query_query_expr),
            'table.data.rows_query.query.value': extra_params.get('table_data_rows_query_query_value', table_data_rows_query_query_value),
            'table.data.cols_query.query.type': extra_params.get('table_data_cols_query_query_type', table_data_cols_query_query_type),
            'table.data.cols_query.query.table': extra_params.get('table_data_cols_query_query_table', table_data_cols_query_query_table),
            'table.data.cols_query.query.cname': extra_params.get('table_data_cols_query_query_cname', table_data_cols_query_query_cname),
            'table.data.cols_query.query.expr': extra_params.get('table_data_cols_query_query_expr', table_data_cols_query_query_expr),
            'table.data.cols_query.query.value': extra_params.get('table_data_cols_query_query_value', table_data_cols_query_query_value),
            'table.data.transforms': extra_params.get('table_data_transforms', table_data_transforms),
            'table.category.enabled': extra_params.get('table_category_enabled', table_category_enabled),
            'table.category.axis': extra_params.get('table_category_axis', table_category_axis),
            'table.category.category.table': extra_params.get('table_category_category_table', table_category_category_table),
            'table.category.category.cname': extra_params.get('table_category_category_cname', table_category_category_cname),
            'table.category.category.label': extra_params.get('table_category_category_label', table_category_category_label),
            'table.category.rows_query.query.type': extra_params.get('table_category_rows_query_query_type', table_category_rows_query_query_type),
            'table.category.rows_query.query.table': extra_params.get('table_category_rows_query_query_table', table_category_rows_query_query_table),
            'table.category.rows_query.query.cname': extra_params.get('table_category_rows_query_query_cname', table_category_rows_query_query_cname),
            'table.category.rows_query.query.expr': extra_params.get('table_category_rows_query_query_expr', table_category_rows_query_query_expr),
            'table.category.rows_query.query.value': extra_params.get('table_category_rows_query_query_value', table_category_rows_query_query_value),
            'table.category.cols_query.query.type': extra_params.get('table_category_cols_query_query_type', table_category_cols_query_query_type),
            'table.category.cols_query.query.table': extra_params.get('table_category_cols_query_query_table', table_category_cols_query_query_table),
            'table.category.cols_query.query.cname': extra_params.get('table_category_cols_query_query_cname', table_category_cols_query_query_cname),
            'table.category.cols_query.query.expr': extra_params.get('table_category_cols_query_query_expr', table_category_cols_query_query_expr),
            'table.category.cols_query.query.value': extra_params.get('table_category_cols_query_query_value', table_category_cols_query_query_value),
            'table.category.transforms': extra_params.get('table_category_transforms', table_category_transforms),
            'variable_options.axis': extra_params.get('variable_options_axis', variable_options_axis),
            'variable_options.log_values': extra_params.get('variable_options_log_values', variable_options_log_values),
            'variable_options.sort_by': extra_params.get('variable_options_sort_by', variable_options_sort_by),
            'category_options.axis': extra_params.get('category_options_axis', category_options_axis),
            'category_options.sort_by': extra_params.get('category_options_sort_by', category_options_sort_by),
            'display_options.ncols': extra_params.get('display_options_ncols', display_options_ncols),
            'display_options.outliers.enabled': extra_params.get('display_options_outliers_enabled', display_options_outliers_enabled),
            'display_options.title': extra_params.get('display_options_title', display_options_title),
            'display_options.var_label': extra_params.get('display_options_var_label', display_options_var_label),
            'display_options.val_label': extra_params.get('display_options_val_label', display_options_val_label),
            'display_options.height': extra_params.get('display_options_height', display_options_height)
        }
    )
