# THIS FILE IS AUTOGENERATED

from mudata_explorer.sdk.helpers import collapse_params
from mudata_explorer.helpers.add_view import add_view
from muon import MuData


def plotly_category_count(
    mdata: MuData,
    data_sidebar=False,
    data_axis=0,
    data_axis_sidebar=False,
    data_x_table=None,
    data_x_table_sidebar=False,
    data_x_cname=None,
    data_x_cname_sidebar=False,
    data_x_label='x-axis',
    data_x_label_sidebar=False,
    data_color_table=None,
    data_color_table_sidebar=False,
    data_color_cname=None,
    data_color_cname_sidebar=False,
    data_color_label='Color',
    data_color_label_sidebar=False,
    data_color_enabled=True,
    data_color_enabled_sidebar=False,
    data_color_is_categorical=True,
    data_color_is_categorical_sidebar=False,
    data_color_scale='D3',
    data_color_scale_sidebar=False,
    data_rows_query_query_type='',
    data_rows_query_query_sidebar=False,
    data_rows_query_query_table='',
    data_rows_query_query_cname='',
    data_rows_query_query_expr='',
    data_rows_query_query_value='',
    data_cols_query_query_type='',
    data_cols_query_query_sidebar=False,
    data_cols_query_query_table='',
    data_cols_query_query_cname='',
    data_cols_query_query_expr='',
    data_cols_query_query_value='',
    data_transforms=[],
    data_transforms_sidebar=False,
    ylabel_sidebar=False,
    ylabel='Count',
    barmode_sidebar=False,
    barmode=None,
    scale_options_sidebar=False,
    scale_options_log_y_sidebar=False,
    scale_options_log_y=None,
    formatting_sidebar=False,
    formatting_title_sidebar=False,
    formatting_title='',
    annotation_options_sidebar=False,
    annotation_options_show_values_sidebar=False,
    annotation_options_show_values=None,
    annotation_options_chisquare_sidebar=False,
    annotation_options_chisquare=None,
    **extra_params
):
    """
    
    Show a bar graph which depicts the values in a single column,
    showing the number of times that each unique value is present.
    This is a frequency histogram showing categorical values.

    Optionally, a second column can be used to color the bars.
    When the color column is used, the position may be set to either
    stack vertically, or to group the bars side by side.
    
    """

    assert isinstance(mdata, MuData), "mdata must be a MuData object"
    extra_params = collapse_params(extra_params)

    add_view(
        'plotly-category-count',
        mdata,
        params={
            'data.sidebar': extra_params.get('data_sidebar', data_sidebar),
            'data.axis': extra_params.get('data_axis', data_axis),
            'data.axis.sidebar': extra_params.get('data_axis_sidebar', data_axis_sidebar),
            'data.x.table': extra_params.get('data_x_table', data_x_table),
            'data.x.table.sidebar': extra_params.get('data_x_table_sidebar', data_x_table_sidebar),
            'data.x.cname': extra_params.get('data_x_cname', data_x_cname),
            'data.x.cname.sidebar': extra_params.get('data_x_cname_sidebar', data_x_cname_sidebar),
            'data.x.label': extra_params.get('data_x_label', data_x_label),
            'data.x.label.sidebar': extra_params.get('data_x_label_sidebar', data_x_label_sidebar),
            'data.color.table': extra_params.get('data_color_table', data_color_table),
            'data.color.table.sidebar': extra_params.get('data_color_table_sidebar', data_color_table_sidebar),
            'data.color.cname': extra_params.get('data_color_cname', data_color_cname),
            'data.color.cname.sidebar': extra_params.get('data_color_cname_sidebar', data_color_cname_sidebar),
            'data.color.label': extra_params.get('data_color_label', data_color_label),
            'data.color.label.sidebar': extra_params.get('data_color_label_sidebar', data_color_label_sidebar),
            'data.color.enabled': extra_params.get('data_color_enabled', data_color_enabled),
            'data.color.enabled.sidebar': extra_params.get('data_color_enabled_sidebar', data_color_enabled_sidebar),
            'data.color.is_categorical': extra_params.get('data_color_is_categorical', data_color_is_categorical),
            'data.color.is_categorical.sidebar': extra_params.get('data_color_is_categorical_sidebar', data_color_is_categorical_sidebar),
            'data.color.scale': extra_params.get('data_color_scale', data_color_scale),
            'data.color.scale.sidebar': extra_params.get('data_color_scale_sidebar', data_color_scale_sidebar),
            'data.rows_query.query.type': extra_params.get('data_rows_query_query_type', data_rows_query_query_type),
            'data.rows_query.query.sidebar': extra_params.get('data_rows_query_query_sidebar', data_rows_query_query_sidebar),
            'data.rows_query.query.table': extra_params.get('data_rows_query_query_table', data_rows_query_query_table),
            'data.rows_query.query.cname': extra_params.get('data_rows_query_query_cname', data_rows_query_query_cname),
            'data.rows_query.query.expr': extra_params.get('data_rows_query_query_expr', data_rows_query_query_expr),
            'data.rows_query.query.value': extra_params.get('data_rows_query_query_value', data_rows_query_query_value),
            'data.cols_query.query.type': extra_params.get('data_cols_query_query_type', data_cols_query_query_type),
            'data.cols_query.query.sidebar': extra_params.get('data_cols_query_query_sidebar', data_cols_query_query_sidebar),
            'data.cols_query.query.table': extra_params.get('data_cols_query_query_table', data_cols_query_query_table),
            'data.cols_query.query.cname': extra_params.get('data_cols_query_query_cname', data_cols_query_query_cname),
            'data.cols_query.query.expr': extra_params.get('data_cols_query_query_expr', data_cols_query_query_expr),
            'data.cols_query.query.value': extra_params.get('data_cols_query_query_value', data_cols_query_query_value),
            'data.transforms': extra_params.get('data_transforms', data_transforms),
            'data.transforms.sidebar': extra_params.get('data_transforms_sidebar', data_transforms_sidebar),
            'ylabel.sidebar': extra_params.get('ylabel_sidebar', ylabel_sidebar),
            'ylabel': extra_params.get('ylabel', ylabel),
            'barmode.sidebar': extra_params.get('barmode_sidebar', barmode_sidebar),
            'barmode': extra_params.get('barmode', barmode),
            'scale_options.sidebar': extra_params.get('scale_options_sidebar', scale_options_sidebar),
            'scale_options.log_y.sidebar': extra_params.get('scale_options_log_y_sidebar', scale_options_log_y_sidebar),
            'scale_options.log_y': extra_params.get('scale_options_log_y', scale_options_log_y),
            'formatting.sidebar': extra_params.get('formatting_sidebar', formatting_sidebar),
            'formatting.title.sidebar': extra_params.get('formatting_title_sidebar', formatting_title_sidebar),
            'formatting.title': extra_params.get('formatting_title', formatting_title),
            'annotation_options.sidebar': extra_params.get('annotation_options_sidebar', annotation_options_sidebar),
            'annotation_options.show_values.sidebar': extra_params.get('annotation_options_show_values_sidebar', annotation_options_show_values_sidebar),
            'annotation_options.show_values': extra_params.get('annotation_options_show_values', annotation_options_show_values),
            'annotation_options.chisquare.sidebar': extra_params.get('annotation_options_chisquare_sidebar', annotation_options_chisquare_sidebar),
            'annotation_options.chisquare': extra_params.get('annotation_options_chisquare', annotation_options_chisquare)
        }
    )
