# THIS FILE IS AUTOGENERATED

from mudata_explorer.sdk.helpers import collapse_params
from mudata_explorer.helpers.add_view import add_view
from muon import MuData


def plotly_scatter(
    mdata: MuData,
    data_sidebar=False,
    data_axis=0,
    data_axis_sidebar=False,
    data_x_table=None,
    data_x_table_sidebar=False,
    data_x_cname=None,
    data_x_cname_sidebar=False,
    data_x_label='x-axis',
    data_x_label_sidebar=False,
    data_y_table=None,
    data_y_table_sidebar=False,
    data_y_cname=None,
    data_y_cname_sidebar=False,
    data_y_label='y-axis',
    data_y_label_sidebar=False,
    data_size_table=None,
    data_size_table_sidebar=False,
    data_size_cname=None,
    data_size_cname_sidebar=False,
    data_size_label='size',
    data_size_label_sidebar=False,
    data_size_enabled=True,
    data_size_enabled_sidebar=False,
    data_color_table=None,
    data_color_table_sidebar=False,
    data_color_cname=None,
    data_color_cname_sidebar=False,
    data_color_label='Color',
    data_color_label_sidebar=False,
    data_color_enabled=True,
    data_color_enabled_sidebar=False,
    data_color_is_categorical=False,
    data_color_is_categorical_sidebar=False,
    data_color_scale='Viridis',
    data_color_scale_sidebar=False,
    data_rows_query_query_type='',
    data_rows_query_query_sidebar=False,
    data_rows_query_query_table='',
    data_rows_query_query_cname='',
    data_rows_query_query_expr='',
    data_rows_query_query_value='',
    data_cols_query_query_type='',
    data_cols_query_query_sidebar=False,
    data_cols_query_query_table='',
    data_cols_query_query_cname='',
    data_cols_query_query_expr='',
    data_cols_query_query_value='',
    data_transforms=[],
    data_transforms_sidebar=False,
    scale_options_sidebar=False,
    scale_options_log_x_sidebar=False,
    scale_options_log_x=None,
    scale_options_log_y_sidebar=False,
    scale_options_log_y=None,
    formatting_sidebar=False,
    formatting_opacity_sidebar=False,
    formatting_opacity=1.0,
    formatting_title_sidebar=False,
    formatting_title='',
    **extra_params
):
    """
    
Display a two dimensional distribution of data using Plotly.

In addition to the data used for the x- and y-axes, the size and color
of the points can be set to represent additional dimensions of the data.

Additional formatting options include setting the opacity of the points
and using a log scale for the x- and y-axes.

    """

    assert isinstance(mdata, MuData), "mdata must be a MuData object"
    extra_params = collapse_params(extra_params)

    add_view(
        'plotly-scatter',
        mdata,
        params={
            'data.sidebar': extra_params.get('data_sidebar', data_sidebar),
            'data.axis': extra_params.get('data_axis', data_axis),
            'data.axis.sidebar': extra_params.get('data_axis_sidebar', data_axis_sidebar),
            'data.x.table': extra_params.get('data_x_table', data_x_table),
            'data.x.table.sidebar': extra_params.get('data_x_table_sidebar', data_x_table_sidebar),
            'data.x.cname': extra_params.get('data_x_cname', data_x_cname),
            'data.x.cname.sidebar': extra_params.get('data_x_cname_sidebar', data_x_cname_sidebar),
            'data.x.label': extra_params.get('data_x_label', data_x_label),
            'data.x.label.sidebar': extra_params.get('data_x_label_sidebar', data_x_label_sidebar),
            'data.y.table': extra_params.get('data_y_table', data_y_table),
            'data.y.table.sidebar': extra_params.get('data_y_table_sidebar', data_y_table_sidebar),
            'data.y.cname': extra_params.get('data_y_cname', data_y_cname),
            'data.y.cname.sidebar': extra_params.get('data_y_cname_sidebar', data_y_cname_sidebar),
            'data.y.label': extra_params.get('data_y_label', data_y_label),
            'data.y.label.sidebar': extra_params.get('data_y_label_sidebar', data_y_label_sidebar),
            'data.size.table': extra_params.get('data_size_table', data_size_table),
            'data.size.table.sidebar': extra_params.get('data_size_table_sidebar', data_size_table_sidebar),
            'data.size.cname': extra_params.get('data_size_cname', data_size_cname),
            'data.size.cname.sidebar': extra_params.get('data_size_cname_sidebar', data_size_cname_sidebar),
            'data.size.label': extra_params.get('data_size_label', data_size_label),
            'data.size.label.sidebar': extra_params.get('data_size_label_sidebar', data_size_label_sidebar),
            'data.size.enabled': extra_params.get('data_size_enabled', data_size_enabled),
            'data.size.enabled.sidebar': extra_params.get('data_size_enabled_sidebar', data_size_enabled_sidebar),
            'data.color.table': extra_params.get('data_color_table', data_color_table),
            'data.color.table.sidebar': extra_params.get('data_color_table_sidebar', data_color_table_sidebar),
            'data.color.cname': extra_params.get('data_color_cname', data_color_cname),
            'data.color.cname.sidebar': extra_params.get('data_color_cname_sidebar', data_color_cname_sidebar),
            'data.color.label': extra_params.get('data_color_label', data_color_label),
            'data.color.label.sidebar': extra_params.get('data_color_label_sidebar', data_color_label_sidebar),
            'data.color.enabled': extra_params.get('data_color_enabled', data_color_enabled),
            'data.color.enabled.sidebar': extra_params.get('data_color_enabled_sidebar', data_color_enabled_sidebar),
            'data.color.is_categorical': extra_params.get('data_color_is_categorical', data_color_is_categorical),
            'data.color.is_categorical.sidebar': extra_params.get('data_color_is_categorical_sidebar', data_color_is_categorical_sidebar),
            'data.color.scale': extra_params.get('data_color_scale', data_color_scale),
            'data.color.scale.sidebar': extra_params.get('data_color_scale_sidebar', data_color_scale_sidebar),
            'data.rows_query.query.type': extra_params.get('data_rows_query_query_type', data_rows_query_query_type),
            'data.rows_query.query.sidebar': extra_params.get('data_rows_query_query_sidebar', data_rows_query_query_sidebar),
            'data.rows_query.query.table': extra_params.get('data_rows_query_query_table', data_rows_query_query_table),
            'data.rows_query.query.cname': extra_params.get('data_rows_query_query_cname', data_rows_query_query_cname),
            'data.rows_query.query.expr': extra_params.get('data_rows_query_query_expr', data_rows_query_query_expr),
            'data.rows_query.query.value': extra_params.get('data_rows_query_query_value', data_rows_query_query_value),
            'data.cols_query.query.type': extra_params.get('data_cols_query_query_type', data_cols_query_query_type),
            'data.cols_query.query.sidebar': extra_params.get('data_cols_query_query_sidebar', data_cols_query_query_sidebar),
            'data.cols_query.query.table': extra_params.get('data_cols_query_query_table', data_cols_query_query_table),
            'data.cols_query.query.cname': extra_params.get('data_cols_query_query_cname', data_cols_query_query_cname),
            'data.cols_query.query.expr': extra_params.get('data_cols_query_query_expr', data_cols_query_query_expr),
            'data.cols_query.query.value': extra_params.get('data_cols_query_query_value', data_cols_query_query_value),
            'data.transforms': extra_params.get('data_transforms', data_transforms),
            'data.transforms.sidebar': extra_params.get('data_transforms_sidebar', data_transforms_sidebar),
            'scale_options.sidebar': extra_params.get('scale_options_sidebar', scale_options_sidebar),
            'scale_options.log_x.sidebar': extra_params.get('scale_options_log_x_sidebar', scale_options_log_x_sidebar),
            'scale_options.log_x': extra_params.get('scale_options_log_x', scale_options_log_x),
            'scale_options.log_y.sidebar': extra_params.get('scale_options_log_y_sidebar', scale_options_log_y_sidebar),
            'scale_options.log_y': extra_params.get('scale_options_log_y', scale_options_log_y),
            'formatting.sidebar': extra_params.get('formatting_sidebar', formatting_sidebar),
            'formatting.opacity.sidebar': extra_params.get('formatting_opacity_sidebar', formatting_opacity_sidebar),
            'formatting.opacity': extra_params.get('formatting_opacity', formatting_opacity),
            'formatting.title.sidebar': extra_params.get('formatting_title_sidebar', formatting_title_sidebar),
            'formatting.title': extra_params.get('formatting_title', formatting_title)
        }
    )
