# THIS FILE IS AUTOGENERATED

from mudata_explorer import app
from mudata_explorer.sdk.helpers import collapse_params
from muon import MuData


def plotly_category_summarize_values(
    mdata: MuData,
    table_data_axis=0,
    table_data_tables=[],
    table_data_rows_query_query_type='',
    table_data_rows_query_query_table='',
    table_data_rows_query_query_cname='',
    table_data_rows_query_query_expr='',
    table_data_rows_query_query_value='',
    table_data_cols_query_query_type='',
    table_data_cols_query_query_table='',
    table_data_cols_query_query_cname='',
    table_data_cols_query_query_expr='',
    table_data_cols_query_query_value='',
    table_data_transforms=[],
    table_category_axis=0,
    table_category_category_table=None,
    table_category_category_cname=None,
    table_category_category_label='Category',
    table_category_rows_query_query_type='',
    table_category_rows_query_query_table='',
    table_category_rows_query_query_cname='',
    table_category_rows_query_query_expr='',
    table_category_rows_query_query_value='',
    table_category_cols_query_query_type='',
    table_category_cols_query_query_table='',
    table_category_cols_query_query_cname='',
    table_category_cols_query_query_expr='',
    table_category_cols_query_query_value='',
    table_category_transforms=[],
    formatting_size='Mean',
    formatting_color='Non-Null',
    **extra_params
):
    """
    
    Summarize the values in a collection of columns,
    grouped by a single column which contains categories.

    The plot will be laid out with the categories on the y-axis,
    and each of the columns will be shown on the x-axis.

    For each of the categories, the values in each of the columns
    will be summarized in terms of:

    - The mean value
    - The median value
    - The number of positive, non-zero values
    - The number of non-null values

    The size and color of the points can be set to represent
    any of those summary statistics.
    
    """

    assert isinstance(mdata, MuData), "mdata must be a MuData object"
    extra_params = collapse_params(extra_params)

    app.add_view(
        'plotly-category-summarize-values',
        mdata,
        params={
            'table.data.axis': extra_params.get('table_data_axis', table_data_axis),
            'table.data.tables': extra_params.get('table_data_tables', table_data_tables),
            'table.data.rows_query.query.type': extra_params.get('table_data_rows_query_query_type', table_data_rows_query_query_type),
            'table.data.rows_query.query.table': extra_params.get('table_data_rows_query_query_table', table_data_rows_query_query_table),
            'table.data.rows_query.query.cname': extra_params.get('table_data_rows_query_query_cname', table_data_rows_query_query_cname),
            'table.data.rows_query.query.expr': extra_params.get('table_data_rows_query_query_expr', table_data_rows_query_query_expr),
            'table.data.rows_query.query.value': extra_params.get('table_data_rows_query_query_value', table_data_rows_query_query_value),
            'table.data.cols_query.query.type': extra_params.get('table_data_cols_query_query_type', table_data_cols_query_query_type),
            'table.data.cols_query.query.table': extra_params.get('table_data_cols_query_query_table', table_data_cols_query_query_table),
            'table.data.cols_query.query.cname': extra_params.get('table_data_cols_query_query_cname', table_data_cols_query_query_cname),
            'table.data.cols_query.query.expr': extra_params.get('table_data_cols_query_query_expr', table_data_cols_query_query_expr),
            'table.data.cols_query.query.value': extra_params.get('table_data_cols_query_query_value', table_data_cols_query_query_value),
            'table.data.transforms': extra_params.get('table_data_transforms', table_data_transforms),
            'table.category.axis': extra_params.get('table_category_axis', table_category_axis),
            'table.category.category.table': extra_params.get('table_category_category_table', table_category_category_table),
            'table.category.category.cname': extra_params.get('table_category_category_cname', table_category_category_cname),
            'table.category.category.label': extra_params.get('table_category_category_label', table_category_category_label),
            'table.category.rows_query.query.type': extra_params.get('table_category_rows_query_query_type', table_category_rows_query_query_type),
            'table.category.rows_query.query.table': extra_params.get('table_category_rows_query_query_table', table_category_rows_query_query_table),
            'table.category.rows_query.query.cname': extra_params.get('table_category_rows_query_query_cname', table_category_rows_query_query_cname),
            'table.category.rows_query.query.expr': extra_params.get('table_category_rows_query_query_expr', table_category_rows_query_query_expr),
            'table.category.rows_query.query.value': extra_params.get('table_category_rows_query_query_value', table_category_rows_query_query_value),
            'table.category.cols_query.query.type': extra_params.get('table_category_cols_query_query_type', table_category_cols_query_query_type),
            'table.category.cols_query.query.table': extra_params.get('table_category_cols_query_query_table', table_category_cols_query_query_table),
            'table.category.cols_query.query.cname': extra_params.get('table_category_cols_query_query_cname', table_category_cols_query_query_cname),
            'table.category.cols_query.query.expr': extra_params.get('table_category_cols_query_query_expr', table_category_cols_query_query_expr),
            'table.category.cols_query.query.value': extra_params.get('table_category_cols_query_query_value', table_category_cols_query_query_value),
            'table.category.transforms': extra_params.get('table_category_transforms', table_category_transforms),
            'formatting.size': extra_params.get('formatting_size', formatting_size),
            'formatting.color': extra_params.get('formatting_color', formatting_color)
        }
    )
