# THIS FILE IS AUTOGENERATED

from mudata_explorer.sdk.helpers import collapse_params
from mudata_explorer.helpers.add_view import add_view
from mudata import MuData


def supporting_figure(
    mdata: MuData,
    input_value=None,
    input_sidebar=False,
    **extra_params
):
    """
    Display a figure which was generated during an analysis process.
    """

    assert isinstance(mdata, MuData), "mdata must be a MuData object"
    extra_params = collapse_params(extra_params)

    add_view(
        'supporting_figure',
        mdata,
        params={
            'input.value': extra_params.get('input_value', input_value),
            'input.sidebar': extra_params.get('input_sidebar', input_sidebar)
        }
    )
