# THIS FILE IS AUTOGENERATED

from mudata_explorer.sdk.helpers import collapse_params
from mudata_explorer.helpers.add_view import add_view
from muon import MuData


def supporting_figure(
    mdata: MuData,
    input_sidebar=False,
    input=None,
    **extra_params
):
    """
    Display a figure which was generated during an analysis process.
    """

    assert isinstance(mdata, MuData), "mdata must be a MuData object"
    extra_params = collapse_params(extra_params)

    add_view(
        'supporting_figure',
        mdata,
        params={
            'input.sidebar': extra_params.get('input_sidebar', input_sidebar),
            'input': extra_params.get('input', input)
        }
    )
