# THIS FILE IS AUTOGENERATED

from mudata_explorer import app
from mudata_explorer.sdk.helpers import collapse_params
from muon import MuData


def supporting_figure(
    mdata: MuData,
    input=None,
    **extra_params
):
    """
    Display a figure which was generated during an analysis process.
    """

    assert isinstance(mdata, MuData), "mdata must be a MuData object"
    extra_params = collapse_params(extra_params)

    app.add_view(
        'supporting_figure',
        mdata,
        params={
            'input': extra_params.get('input', input)
        }
    )
