# THIS FILE IS AUTOGENERATED

from mudata_explorer.sdk.helpers import collapse_params
from mudata_explorer.helpers.assets import make_process
from muon import MuData


def dbscan(
    mdata: MuData,
    table_sidebar=False,
    table_data_sidebar=False,
    table_data_axis=0,
    table_data_axis_sidebar=False,
    table_data_tables=[],
    table_data_tables_sidebar=False,
    table_data_rows_query_query_type='',
    table_data_rows_query_query_sidebar=False,
    table_data_rows_query_query_table='',
    table_data_rows_query_query_cname='',
    table_data_rows_query_query_expr='',
    table_data_rows_query_query_value='',
    table_data_cols_query_query_type='',
    table_data_cols_query_query_sidebar=False,
    table_data_cols_query_query_table='',
    table_data_cols_query_query_cname='',
    table_data_cols_query_query_expr='',
    table_data_cols_query_query_value='',
    table_data_transforms=[],
    table_data_transforms_sidebar=False,
    clustering_sidebar=False,
    clustering_eps_sidebar=False,
    clustering_eps=0.5,
    clustering_min_samples_sidebar=False,
    clustering_min_samples=5,
    clustering_metric_sidebar=False,
    clustering_metric=None,
    outputs_sidebar=False,
    outputs_dest_key_sidebar=False,
    outputs_dest_key='dbscan',
    **extra_params
):
    """
    
    DBSCAN (Density-Based Spatial Clustering of Applications with Noise)
    is a clustering algorithm that groups together points that are
    closely packed together (points with many nearby neighbors), marking
    as outliers points that lie alone in low-density regions.

    The algorithm works by defining neighborhoods around each point and
    grouping points that are within a certain distance of each other.
    Points that are within the neighborhood of a core point are considered
    part of the same cluster. Points that are within the neighborhood of
    a non-core point but are not core points themselves are considered
    border points. Points that are not within the neighborhood of any
    core points are considered outliers.

    - [Wikipedia: DBSCAN](https://en.wikipedia.org/wiki/DBSCAN)
    - [Explanation of DBSCAN (video)](https://www.youtube.com/watch?v=C3r7tGRe2eI)
    
    """

    assert isinstance(mdata, MuData), "mdata must be a MuData object"
    extra_params = collapse_params(extra_params)

    # Instantiate the process using all of the parameters
    process = make_process(
        'dbscan',
        params={
            'table.sidebar': extra_params.get('table_sidebar', table_sidebar),
            'table.data.sidebar': extra_params.get('table_data_sidebar', table_data_sidebar),
            'table.data.axis': extra_params.get('table_data_axis', table_data_axis),
            'table.data.axis.sidebar': extra_params.get('table_data_axis_sidebar', table_data_axis_sidebar),
            'table.data.tables': extra_params.get('table_data_tables', table_data_tables),
            'table.data.tables.sidebar': extra_params.get('table_data_tables_sidebar', table_data_tables_sidebar),
            'table.data.rows_query.query.type': extra_params.get('table_data_rows_query_query_type', table_data_rows_query_query_type),
            'table.data.rows_query.query.sidebar': extra_params.get('table_data_rows_query_query_sidebar', table_data_rows_query_query_sidebar),
            'table.data.rows_query.query.table': extra_params.get('table_data_rows_query_query_table', table_data_rows_query_query_table),
            'table.data.rows_query.query.cname': extra_params.get('table_data_rows_query_query_cname', table_data_rows_query_query_cname),
            'table.data.rows_query.query.expr': extra_params.get('table_data_rows_query_query_expr', table_data_rows_query_query_expr),
            'table.data.rows_query.query.value': extra_params.get('table_data_rows_query_query_value', table_data_rows_query_query_value),
            'table.data.cols_query.query.type': extra_params.get('table_data_cols_query_query_type', table_data_cols_query_query_type),
            'table.data.cols_query.query.sidebar': extra_params.get('table_data_cols_query_query_sidebar', table_data_cols_query_query_sidebar),
            'table.data.cols_query.query.table': extra_params.get('table_data_cols_query_query_table', table_data_cols_query_query_table),
            'table.data.cols_query.query.cname': extra_params.get('table_data_cols_query_query_cname', table_data_cols_query_query_cname),
            'table.data.cols_query.query.expr': extra_params.get('table_data_cols_query_query_expr', table_data_cols_query_query_expr),
            'table.data.cols_query.query.value': extra_params.get('table_data_cols_query_query_value', table_data_cols_query_query_value),
            'table.data.transforms': extra_params.get('table_data_transforms', table_data_transforms),
            'table.data.transforms.sidebar': extra_params.get('table_data_transforms_sidebar', table_data_transforms_sidebar),
            'clustering.sidebar': extra_params.get('clustering_sidebar', clustering_sidebar),
            'clustering.eps.sidebar': extra_params.get('clustering_eps_sidebar', clustering_eps_sidebar),
            'clustering.eps': extra_params.get('clustering_eps', clustering_eps),
            'clustering.min_samples.sidebar': extra_params.get('clustering_min_samples_sidebar', clustering_min_samples_sidebar),
            'clustering.min_samples': extra_params.get('clustering_min_samples', clustering_min_samples),
            'clustering.metric.sidebar': extra_params.get('clustering_metric_sidebar', clustering_metric_sidebar),
            'clustering.metric': extra_params.get('clustering_metric', clustering_metric),
            'outputs.sidebar': extra_params.get('outputs_sidebar', outputs_sidebar),
            'outputs.dest_key.sidebar': extra_params.get('outputs_dest_key_sidebar', outputs_dest_key_sidebar),
            'outputs.dest_key': extra_params.get('outputs_dest_key', outputs_dest_key)
        },
        mdata=mdata,
        params_editable=False
    )

    assert process.params_editable is False, "params_editable must be False"
    assert isinstance(process.mdata, MuData), type(process.mdata)

    # Get the data from the object
    process.get_data()

    # Run the process
    process.execute()

